version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: pumu
    binary: pumu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: pumu
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: carlosedujs
    name: pumu
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Pumu {{ .Tag }} Release

    Thanks for using Pumu! 🧹

  footer: |
    **Full Changelog**: https://github.com/carlosedujs/pumu/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Installation

    ### Binary Downloads
    Download the appropriate binary for your system from the assets below.

    ### Manual Installation
    ```bash
    # Download the appropriate binary for your system
    # Extract and move to /usr/local/bin or add to PATH
    ```

brews:
  - name: pumu
    repository:
      owner: carlosedujs
      name: homebrew-pumu
    directory: Formula
    homepage: https://github.com/carlosedujs/pumu
    description: "Fast, concurrent disk space management tool for developers"
    license: MIT
    install: |
      bin.install "pumu"
    test: |
      system "#{bin}/pumu", "--version"
    url_template: "https://github.com/carlosedujs/pumu/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Carlos Edu (via Goreleaser)
      email: carloseduardogit@gmail.com

    caveats: |
      Pumu is a CLI to clean heavy dependency folders.
      Run `pumu --help` for usage.
      For interactive mode: just `pumu` or `pumu sweep`.

nfpms:
  - id: pumu
    package_name: pumu
    vendor: Carlos
    homepage: https://github.com/carlosedujs/pumu
    maintainer: Carlos
    description: Fast, concurrent disk space management tool for developers
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies: []
    recommends: []

announce:
  skip: true
